### ISSUE TITLE
Applier error: Material must be a block!

### ISSUE THREAD

**Issue by syokkendesuyo** [AddstarMC/Prism-Bukkit#128]
Server: git-Spigot-8faa8b4-13ed05d (MC: 1.15.2)
Prism: v2.1.5-106

An error occurred in the following operation.

`/pr wand rollback`
Specify the location of the destroyed powered_rail (off).

![image](https://user-images.githubusercontent.com/5967134/76195142-00842f00-622b-11ea-8705-b54fff4705ec.png)

> [17:22:46] [Server thread/INFO]: [Prism]: Applier error: Material must be a block!
[17:22:46] [Server thread/WARN]: java.lang.IllegalArgumentException: Material must be a block!
[17:22:46] [Server thread/WARN]:        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
[17:22:46] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.block.CraftBlockState.setType(CraftBlockState.java:133)
[17:22:46] [Server thread/WARN]:        at me.botsko.prism.actions.BlockAction.placeBlock(BlockAction.java:382)
[17:22:46] [Server thread/WARN]:        at me.botsko.prism.actions.BlockAction.applyRollback(BlockAction.java:270)
[17:22:46] [Server thread/WARN]:        at me.botsko.prism.appliers.Preview.lambda$processWorldChanges$0(Preview.java:299)
[17:22:46] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81)
[17:22:46] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394)
[17:22:46] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036)
[17:22:46] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406)
[17:22:46] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984)
[17:22:46] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824)
[17:22:46] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by Narimm** [comment]
Please use the development release here 
https://jenkins.addstar.com.au/job/Prism-Bukkit/

I could not replicate the fault.  That being said I do believe "wand" rollbacks are consistent and I would not use them

I tested with the following 
1. Placed 3 powered rails  - and placed a torch to power 1 of them.
2,  broke all 3 rails
4. Ran `pr l a:break t:1m` and confirmed it showed the three breaks.
```
[20:45:54] [Render thread/INFO]: [CHAT] Prism // Showing 2 results. Page 1 of 1
[20:45:54] [Render thread/INFO]: [CHAT]  - [1] Narimm broke powered rail x2 just now (a:break)
[20:45:54] [Render thread/INFO]: [CHAT]  - [2] Narimm broke powered rail just now (a:break)
```
4. Ran `pr rb a;break t:5m`
```
[20:49:36] [Render thread/INFO]: [CHAT] Prism // Preparing results...
[20:49:36] [Render thread/INFO]: [CHAT] Prism // Beginning rollback...
[20:49:36] [Render thread/INFO]: [CHAT] [!] rollback by Narimm r:1 a:break t:5m -extended
[20:49:36] [Render thread/INFO]: [CHAT] Prism // 3 reversals. It's like it never happened.
```
Could not replicate.

**Comment by Narimm** [comment]
If the break occured prior to 1.15 then it will probably fail.  Other than that I would need to see the db line entry

**Comment by addstar** [comment]
No response - Please try the latest builds and open a new issue if its still happening
