### ISSUE TITLE
[BUG] Database connection error: FUNCTION minecraft.any_value does not exist

### ISSUE THREAD

**Issue by viveleroi** [AddstarMC/Prism-Bukkit#173]
**Describe the bug**
Trying to perform a lookup, console shows the below error/stacktrace.

**To Reproduce**
I installed it on a new paper 1.15.2 server, connected it to a MariaDB server.

Logging works fine, I see data, queried my actions via SQL. But any lookup/near command via Prism fails.

**Expected behavior**
Shouldn't fail

**Screenshots**
N/A

**Server (please complete the following information):**
  - Prism Version: 2.1.6
  - Server Type: Paper b264
  - Server Version: 1.15.2

**Additional context**

```
[17:31:58] [Craft Scheduler Thread - 2658/ERROR]: [Prism] Database connection error: FUNCTION minecraft.any_value does not exist
[17:31:58] [Craft Scheduler Thread - 2658/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: FUNCTION minecraft.any_value does not exist
[17:31:58] [Craft Scheduler Thread - 2658/WARN]: 	at jdk.internal.reflect.GeneratedConstructorAccessor69.newInstance(Unknown Source)
[17:31:58] [Craft Scheduler Thread - 2658/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[17:31:58] [Craft Scheduler Thread - 2658/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[17:31:58] [Craft Scheduler Thread - 2658/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[17:31:58] [Craft Scheduler Thread - 2658/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
[17:31:58] [Craft Scheduler Thread - 2658/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[17:31:58] [Craft Scheduler Thread - 2658/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
[17:31:58] [Craft Scheduler Thread - 2658/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
[17:31:58] [Craft Scheduler Thread - 2658/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[17:31:58] [Craft Scheduler Thread - 2658/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
[17:31:58] [Craft Scheduler Thread - 2658/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
[17:31:58] [Craft Scheduler Thread - 2658/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1912)
[17:31:58] [Craft Scheduler Thread - 2658/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2020)
[17:31:58] [Craft Scheduler Thread - 2658/WARN]: 	at com.botsko.prism.libs.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
[17:31:58] [Craft Scheduler Thread - 2658/WARN]: 	at com.botsko.prism.libs.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
[17:31:58] [Craft Scheduler Thread - 2658/WARN]: 	at me.botsko.prism.database.sql.SQLSelectQueryBuilder.executeSelect(SQLSelectQueryBuilder.java:526)
[17:31:58] [Craft Scheduler Thread - 2658/WARN]: 	at me.botsko.prism.actionlibs.ActionsQuery.lookup(ActionsQuery.java:81)
[17:31:58] [Craft Scheduler Thread - 2658/WARN]: 	at me.botsko.prism.commands.NearCommand.lambda$handle$0(NearCommand.java:76)
[17:31:58] [Craft Scheduler Thread - 2658/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[17:31:58] [Craft Scheduler Thread - 2658/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[17:31:58] [Craft Scheduler Thread - 2658/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:31:58] [Craft Scheduler Thread - 2658/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[17:31:58] [Craft Scheduler Thread - 2658/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[17:31:58] [Craft Scheduler Thread - 2658/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Narimm** [comment]
This is covered in the 2.1.7 update - but reading the load log on a 2.1.6 server will tell you why its an issue

**Comment by gp-Airee** [comment]
This seems to be happening again in 2.1.7.

```
> pr version
[07:08:22 INFO]: Prism // Prism - originally by Viveleroi; maintained by The AddstarMC Network v2.1.7-
[07:08:22 INFO]: Prism // Help: /pr ?
[07:08:22 INFO]: Prism // Discord: https://discord.gg/Y9Qx3V
[07:08:22 INFO]: Prism // Wiki: https://github.com/AddstarMC/Prism-Bukkit/wiki
> ver
[07:08:37 INFO]: This server is running Tuinity version git-Seednity-921f191 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[07:08:37 INFO]: Checking version, please wait...
[07:08:37 INFO]: Unknown version
> ver Prism
[07:08:38 INFO]: Prism version 2.1.7-
[07:08:38 INFO]: Website: https://github.com/AddstarMC/Prism-Bukkit/wiki
[07:08:38 INFO]: Authors: AddstarMC, add5tar, Narimm and viveleroi
[07:08:42 ERROR]: [Prism] Database connection error: FUNCTION prism_test.any_value does not exist
[07:08:42 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: FUNCTION prism_test.any_value does not exist
[07:08:42 WARN]:        at jdk.internal.reflect.GeneratedConstructorAccessor37.newInstance(Unknown Source)
[07:08:42 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[07:08:42 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[07:08:42 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[07:08:42 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:403)
[07:08:42 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:386)
[07:08:42 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[07:08:42 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
[07:08:42 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
[07:08:42 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[07:08:42 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
[07:08:42 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
[07:08:42 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1915)
[07:08:42 WARN]:        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2023)
[07:08:42 WARN]:        at com.botsko.prism.libs.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
[07:08:42 WARN]:        at com.botsko.prism.libs.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
[07:08:42 WARN]:        at me.botsko.prism.database.sql.SqlSelectQueryBuilder.executeSelect(SqlSelectQueryBuilder.java:473)
[07:08:42 WARN]:        at me.botsko.prism.actionlibs.ActionsQuery.lookup(ActionsQuery.java:65)
[07:08:42 WARN]:        at me.botsko.prism.wands.QueryWandBase.getResult(QueryWandBase.java:75)
[07:08:42 WARN]:        at me.botsko.prism.wands.InspectorWand.lambda$showLocationHistory$46(InspectorWand.java:85)
[07:08:42 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
[07:08:42 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
[07:08:42 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[07:08:42 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[07:08:42 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[07:08:42 WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)

```

**Comment by Narimm** [comment]
Honestly if your here with this issue you have not read the doc's or the support channel notes. This is not an issue this is poor configuration on the user's behalf
