### ISSUE TITLE
[BUG] NPE when killing Armor Stand with commands

### ISSUE THREAD

**Issue by robertoccu** [AddstarMC/Prism-Bukkit#186]
**Describe the bug**
When an Armor Stand is

**To Reproduce**
Kill an Armor Stand using /minecraft:kill command.

**Expected behavior**
No NPE happens

**Console log**
[13:04:53] [Server thread/ERROR]: Could not pass event EntityDeathEvent to Prism v2.1.6-127
java.lang.NullPointerException: null
	at me.botsko.prism.listeners.PrismEntityEvents.onEntityDeath(PrismEntityEvents.java:163) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor849.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-301]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-301]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-301]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-301]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:767) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.EntityArmorStand.killEntity(EntityArmorStand.java:704) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.CommandKill.a(SourceFile:32) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.CommandKill.a(SourceFile:25) ~[patched_1.15.2.jar:git-Paper-301]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[patched_1.15.2.jar:git-Paper-301]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.CommandDispatcher.a(CommandDispatcher.java:179) ~[patched_1.15.2.jar:git-Paper-301]
	at org.bukkit.craftbukkit.v1_15_R1.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45) ~[patched_1.15.2.jar:git-Paper-301]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-301]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Paper-301]
	at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:461) ~[patched_1.15.2.jar:git-Paper-301]
	at com.denizenscript.denizen.scripts.commands.server.ExecuteCommand.execute(ExecuteCommand.java:185) ~[?:?]
	at com.denizenscript.denizencore.scripts.commands.CommandExecutor.execute(CommandExecutor.java:80) ~[?:?]
	at com.denizenscript.denizencore.scripts.queues.ScriptEngine.revolve(ScriptEngine.java:56) ~[?:?]
	at com.denizenscript.denizencore.scripts.queues.core.InstantQueue.revolve(InstantQueue.java:64) ~[?:?]
	at com.denizenscript.denizencore.scripts.queues.core.InstantQueue.onStart(InstantQueue.java:54) ~[?:?]
	at com.denizenscript.denizencore.scripts.queues.ScriptQueue.runMeNow(ScriptQueue.java:290) ~[?:?]
	at com.denizenscript.denizencore.scripts.queues.ScriptQueue.start(ScriptQueue.java:337) ~[?:?]
	at com.denizenscript.denizencore.scripts.queues.ScriptQueue.start(ScriptQueue.java:298) ~[?:?]
	at com.denizenscript.denizen.scripts.containers.core.CommandScriptContainer.runCommandScript(CommandScriptContainer.java:172) ~[?:?]
	at com.denizenscript.denizen.utilities.command.scripted.DenizenCommand.execute(DenizenCommand.java:161) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-301]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1860) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1668) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1097) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1090) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1051) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:966) ~[patched_1.15.2.jar:git-Paper-301]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

**Server (please complete the following information):**
  - Prism Version: 2.1.6
  - Server Type: Paper 301
  - Server Version: 1.15.2

**Comment by Narimm** [comment]
This is fixed in the 2.1.7-SNAPSHOT but I will say that the error is because denizens is cancelling the lastdamage and thus the entitiy.getLastDamageCause is null...which is stupid.

So its fixed but the logging is not repairable of
