### ISSUE TITLE
[BUG] Radius parameter broken

### ISSUE THREAD

**Issue by Bobcat00** [AddstarMC/Prism-Bukkit#191]
**Describe the bug**
Increasing the radius provides fewer results.

**To Reproduce**
Issued the following command:
/pr l r:5 t:15d p:dishwashes
![prism_rasius1](https://user-images.githubusercontent.com/3617206/83204239-53c69900-a119-11ea-95ed-445522817b56.png)

At the same location, changed the radius to 50:
/pr l r:50 t:15d p:dishwashes
![prism_radius2](https://user-images.githubusercontent.com/3617206/83204252-57f2b680-a119-11ea-8d7b-7eae10e4e02a.png)

**Expected behavior**
A larger radius should encompass all the results in the smaller radius.

**Server (please complete the following information):**
  - v2.1.7-SNAPSHOT-160
  - Spigot
  - git-Spigot-2f5d615-cfeef75 (MC: 1.15.2)

**Comment by Bobcat00** [comment]
Same results in build 161.

**Comment by viveleroi** [comment]
Not sure if this is related but I had a creeper blow up something and doing `/pr near` showed several results that didn't show in `/pr l r:10`.

**Comment by Bobcat00** [comment]
OK, so I see the following in the server log file when specifying r:50:
[Prism] Prism database error. Connection missing. Leaving actions to log in queue.

Tried build 148, but that gives me an exception at prism.utils.MiscUtils.niceName(MiscUtils.java:107)

**Comment by Bobcat00** [comment]
> Not sure if this is related but I had a creeper blow up something and doing `/pr near` showed several results that didn't show in `/pr l r:10`.

Yeah, I saw something like that too.

**Comment by Narimm** [comment]
> OK, so I see the following in the server log file when specifying r:50:
> [Prism] Prism database error. Connection missing. Leaving actions to log in queue.
> 
> Tried build 148, but that gives me an exception at prism.utils.MiscUtils.niceName(MiscUtils.java:107)

Posting the exceptions is helpful

**Comment by Bobcat00** [comment]
Remember, this is build 148:
```
2020-05-28 19:48:41 [INFO] Bobcat00 issued server command: /pr version
2020-05-28 19:48:52 [INFO] Bobcat00 issued server command: /pr l r:5 t:15d p:dishwashes
2020-05-28 19:48:58 [INFO] Bobcat00 issued server command: /pr l r:50 t:15d p:dishwashes
2020-05-28 19:48:58 [WARN] [Prism] Plugin Prism v2.1.7-SNAPSHOT-148 generated an exception while executing task 692
java.lang.NullPointerException: null
	at me.botsko.prism.utils.MiscUtils.niceName(MiscUtils.java:107) ~[?:?]
	at me.botsko.prism.actions.entity.EntitySerializer.toString(EntitySerializer.java:144) ~[?:?]
	at me.botsko.prism.actions.EntityAction.getNiceName(EntityAction.java:88) ~[?:?]
	at me.botsko.prism.actionlibs.ActionMessage.getMessage(ActionMessage.java:118) ~[?:?]
	at me.botsko.prism.utils.MiscUtils.sendClickableTpRecord(MiscUtils.java:162) ~[?:?]
	at me.botsko.prism.commands.LookupCommand.lambda$handle$0(LookupCommand.java:113) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[custom.jar:git-Spigot-2f5d615-cfeef75]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [custom.jar:git-Spigot-2f5d615-cfeef75]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by Narimm** [comment]
Cheers

**Comment by Bobcat00** [comment]
I'm _guessing_ the entry involves a chest with a custom name with color codes.

**Comment by Narimm** [comment]
The bug is definitely NOT a `pr l r:?` error its something else...can you enable debug in the config and see if you get any more info

**Comment by Narimm** [comment]
What I mean is that radius isnt broken  - increasing the larger radius may be causing the error but its something inside the circle causing it

**Comment by Narimm** [comment]
I have tested and concluded its range is not broken....range works exactly right.  The exception above is not replicated as chest naming was only added in 161

**Comment by Narimm** [comment]
This may be a database lockup error but I might struggle to replicat that on a small server

**Comment by Bobcat00** [comment]
> increasing the larger radius may be causing the error but its something inside the circle causing it

I agree, but with the lookup not working, I can't tell what it might be.  It could be a block the player placed then broke, so I can't see what it is because it's no longer there.  I do know that there are named chests there, which is why I mentioned it.

If only the Prism web interface worked, then I could look at the data. :-)

**Comment by Narimm** [comment]
I was wondering if it might be due to the fact you used a newer version then rolled back.
There would be data inconsistencies doing that because objects that had extra data don't and vice versa

**Comment by Bobcat00** [comment]
No, the problem occurred before I tried the older version.  However, the data was probably logged by build 129.  It's possible the data was saved incorrectly or in a format incompatible with build 161.

**Comment by Bobcat00** [comment]
> can you enable debug in the config and see if you get any more info

Not particularly interesting:
```
2020-05-29 10:32:05 [INFO] Bobcat00 issued server command: /pr l r:10 t:16d p:dishwashes
2020-05-29 10:32:05 [INFO] [Prism Debug ]: Beginning batch insert from queue. 1590762725725
2020-05-29 10:32:05 [INFO] [Prism Debug ]: Batch insert was commit: 1590762725739
2020-05-29 10:32:05 [INFO] [Prism] Prism database error. Connection missing. Leaving actions to log in queue.
2020-05-29 10:32:05 [INFO] [Prism Debug ]: null
2020-05-29 10:32:05 [INFO] [Prism Debug ]: -- Timer information for last action: --
2020-05-29 10:32:05 [INFO] [Prism Debug ]: query started 0ms
2020-05-29 10:32:05 [INFO] [Prism Debug ]: query returned, building results 22ms
2020-05-29 10:32:05 [INFO] [Prism Debug ]: results object completed 23ms
2020-05-29 10:32:05 [INFO] [Prism Debug ]: Total time: 45ms

2020-05-29 10:32:20 [INFO] Bobcat00 issued server command: /pr l r:11 t:16d p:dishwashes
2020-05-29 10:32:20 [INFO] [Prism] Prism database error. Connection missing. Leaving actions to log in queue.
2020-05-29 10:32:20 [INFO] [Prism Debug ]: null
2020-05-29 10:32:20 [INFO] [Prism Debug ]: -- Timer information for last action: --
2020-05-29 10:32:20 [INFO] [Prism Debug ]: query started 0ms
2020-05-29 10:32:20 [INFO] [Prism Debug ]: query returned, building results 13ms
2020-05-29 10:32:20 [INFO] [Prism Debug ]: results object completed 2ms
2020-05-29 10:32:20 [INFO] [Prism Debug ]: Total time: 15ms
2020-05-29 10:32:20 [INFO] [Prism Debug ]: Beginning batch insert from queue. 1590762740875
2020-05-29 10:32:20 [INFO] [Prism Debug ]: Batch insert was commit: 1590762740891
```
