### ISSUE TITLE
[BUG] Shutdown Errors Queue not empty

### ISSUE THREAD

**Issue by Narimm** [AddstarMC/Prism-Bukkit#217]
**Describe the bug**
Errors on shutdown in appears the queue may not have emptied before Hikari terminates

**To Reproduce**
Shutdown server

**Expected behavior**

**Screenshots**
```log
[18:02:44 INFO]: [Prism] Disabling Prism v2.1.7-SNAPSHOT-10
[18:02:44 INFO]: [com.botsko.prism.libs.hikari.HikariDataSource] prism - Shutdown initiated...
[18:02:44 INFO]: [com.botsko.prism.libs.hikari.HikariDataSource] prism - Shutdown completed.
[18:02:44 INFO]: [Prism] Closing plugin.
[18:02:44 WARN]: [com.botsko.prism.libs.hikari.pool.ProxyConnection] prism - Connection com.mysql.jdbc.JDBC4Connection@2687b34b marked as broken because of SQLSTATE(08S01), ErrorCode(0)
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
The last packet successfully received from the server was 174 milliseconds ago.The last packet sent successfully to the server was 174 milliseconds ago.
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_242]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_242]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_242]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_242]
at com.mysql.jdbc.Util.handleNewInstance(Util.java:403) ~[patched_1.16.2.jar:git-Paper-174]
at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990) ~[patched_1.16.2.jar:git-Paper-174]
at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3517) ~[patched_1.16.2.jar:git-Paper-174]
at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3417) ~[patched_1.16.2.jar:git-Paper-174]
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524) ~[patched_1.16.2.jar:git-Paper-174]
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675) ~[patched_1.16.2.jar:git-Paper-174]
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465) ~[patched_1.16.2.jar:git-Paper-174]
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3860) ~[patched_1.16.2.jar:git-Paper-174]
at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2136) ~[patched_1.16.2.jar:git-Paper-174]
at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2070) ~[patched_1.16.2.jar:git-Paper-174]
at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5187) ~[patched_1.16.2.jar:git-Paper-174]
at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2055) ~[patched_1.16.2.jar:git-Paper-174]
at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1915) ~[patched_1.16.2.jar:git-Paper-174]
at com.botsko.prism.libs.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[?:?]
at me.botsko.prism.actionlibs.RecordingTask.insertActionsIntoDatabase(RecordingTask.java:118) ~[?:?]
at me.botsko.prism.database.sql.SqlInsertBuilder.insertActionIntoDatabase(SqlInsertBuilder.java:72) ~[?:?]
at me.botsko.prism.actionlibs.RecordingTask.save(RecordingTask.java:46) ~[?:?]
at me.botsko.prism.actionlibs.RecordingTask.run(RecordingTask.java:156) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.2.jar:git-Paper-174]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.2.jar:git-Paper-174]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.2.jar:git-Paper-174]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_242]
Caused by: java.net.SocketException: Socket closed
at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_242]
at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_242]
at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_242]
at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:101) ~[patched_1.16.2.jar:git-Paper-174]
at com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:144) ~[patched_1.16.2.jar:git-Paper-174]
at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:174) ~[patched_1.16.2.jar:git-Paper-174]
at com.botsko.prism.libs.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[?:?]
at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3427) ~[patched_1.16.2.jar:git-Paper-174]
[18:02:44 WARN]:
... 22 more
[18:02:44 WARN]: The last packet successfully received from the server was 174 milliseconds ago.The last packet sent successfully to the server was 174 milliseconds ago.
at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2966) ~[patched_1.16.2.jar:git-Paper-174]
[18:02:44 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:02:44 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[18:02:44 WARN]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
[18:02:44 WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:02:44 WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[18:02:44 WARN]: at com.mysql.jdbc.Util.handleNewInstance(Util.java:403)
[18:02:44 WARN]: at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
[18:02:44 WARN]: at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3517)
[18:02:44 WARN]: at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3417)
[18:02:44 WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3860)
[18:02:44 WARN]: at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[18:02:44 WARN]: at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
[18:02:44 WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2136)
[18:02:44 WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2070)
[18:02:44 WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2055)
[18:02:44 WARN]: at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
[18:02:44 WARN]: at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1915)
[18:02:44 WARN]: at me.botsko.prism.database.sql.SqlInsertBuilder.insertActionIntoDatabase(SqlInsertBuilder.java:72)
[18:02:44 WARN]: at com.botsko.prism.libs.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[18:02:44 WARN]: at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5187)
[18:02:44 WARN]: at com.botsko.prism.libs.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[18:02:44 WARN]: at me.botsko.prism.actionlibs.RecordingTask.insertActionsIntoDatabase(RecordingTask.java:118)
[18:02:44 WARN]: at me.botsko.prism.actionlibs.RecordingTask.save(RecordingTask.java:46)
[18:02:44 WARN]: at me.botsko.prism.actionlibs.RecordingTask.run(RecordingTask.java:156)
[18:02:44 WARN]: at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
[18:02:44 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[18:02:44 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:02:44 WARN]: at java.lang.Thread.run(Thread.java:748)
[18:02:44 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[18:02:44 WARN]: Caused by: java.net.SocketException: Socket closed
[18:02:44 WARN]: at java.net.SocketInputStream.socketRead0(Native Method)
[18:02:44 WARN]: at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:101)
[18:02:44 WARN]: at java.net.SocketInputStream.read(SocketInputStream.java:171)
[18:02:44 WARN]: at java.net.SocketInputStream.read(SocketInputStream.java:141)
[18:02:44 WARN]: at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[18:02:44 WARN]: at com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:144)
[18:02:44 WARN]: at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2966)
[18:02:44 WARN]: at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3427)
[18:02:44 WARN]: ... 22 more
[18:02:44 WARN]: at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
[18:02:44 WARN]: at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:174)
[18:02:44 INFO]: [Prism] Could not retrieve a connection
[18:02:44 WARN]: [Prism] Plugin Prism v2.1.7-SNAPSHOT-10 generated an exception while executing task 1388152
java.lang.NullPointerException: null
at me.botsko.prism.database.sql.SqlInsertBuilder.insertActionIntoDatabase(SqlInsertBuilder.java:69) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.2.jar:git-Paper-174]
at me.botsko.prism.actionlibs.RecordingTask.insertActionsIntoDatabase(RecordingTask.java:118) ~[?:?]
at me.botsko.prism.actionlibs.RecordingTask.save(RecordingTask.java:46) ~[?:?]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.2.jar:git-Paper-174]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.2.jar:git-Paper-174]
at me.botsko.prism.actionlibs.RecordingTask.run(RecordingTask.java:156) ~[?:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
[18:02:44 INFO]: [Multiverse-Portals] Disabling Multiverse-Portals v4.1.0-b805
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]```

**Server (please complete the following information):**
  - Prism Version: 2.1.7.10
  - Server Type: Paper
  - Server Version: 176

**Additional context**
Add any other context about the problem here.

**Comment by Narimm** [comment]
I think this is now resolved
