### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by takatalvi** [AddstarMC/Prism-Bukkit#259]
Hi, I recently started getting an error at the end of startup when tries to purge old data. Prism is loaded without issues but then on purge it gives a DB error. Afterwards, writing and reading to/from the DB works without issues and exceptions. I'm on version 2.1.7.6, on the latest Paper (currently 591). Is this something in my config or can it be patched? Thanks!

Startup:
```
[09:30:30 INFO]: [Prism] Enabling Prism v2.1.7-6
[09:30:30 INFO]: [Prism] Initializing Prism 2.1.7-6. Originally by Viveleroi; maintained by the AddstarMC Network
[09:30:30 INFO]: [Prism] Configuring Hikari from hikari.properties
[09:30:30 INFO]: [Prism Debug ]: This file will not save the jdbcURL, username or password - these are loaded by default from the standard prism configuration file. If you set these explicitly in the properties file the settings in the standard config will beignored.
[09:30:30 INFO]: Elixr: Loaded items directory
[09:30:30 INFO]: [Prism] WorldEdit found. Associated features enabled.
[09:30:30 INFO]: [Prism] Prism bStats metrics are enabled - thank you!
[09:30:30 INFO]: [Prism] Attempting to configure datasource as mysql
[09:30:30 INFO]: [Prism] No metric recorder found to hook into Hikari.
[09:30:30 INFO]: [com.botsko.prism.libs.hikari.HikariDataSource] prism - Starting...
[09:30:30 INFO]: [com.botsko.prism.libs.hikari.HikariDataSource] prism - Start completed.
[09:30:30 INFO]: Done (10.907s)! For help, type "help"
[09:30:30 INFO]: [Prism] Prism detected you database is version:5.7.33-0ubuntu0.18.04.1 / (Ubuntu)
[09:30:30 INFO]: [Prism] You have set nonStandardSql to false
[09:30:30 INFO]: [Prism] You are able to use non standard SQL
[09:30:30 INFO]: [Prism] Prism will use standard sql queries
[09:30:30 INFO]: [Prism] Update check complete: Schema v8
[09:30:31 INFO]: [Prism] Scheduled purge executor beginning new run...
[09:30:31 INFO]: [Prism] Processed parameters for database purge: before:8w
[09:30:31 INFO]: [Prism] Beginning prism database purge cycle. Will be performed in batches so we don't tie up the db...
```

Exception:
```
[09:30:34 ERROR]: [Prism] Database connection error: Operation not allowed for a result set of type ResultSet.TYPE_FORWARD_ONLY.
[09:30:34 WARN]: java.sql.SQLException: Operation not allowed for a result set of type ResultSet.TYPE_FORWARD_ONLY.
[09:30:34 WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
[09:30:34 WARN]: at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[09:30:34 WARN]: at com.mysql.cj.jdbc.result.ResultSetImpl.first(ResultSetImpl.java:603)
[09:30:34 WARN]: at com.botsko.prism.libs.hikari.pool.HikariProxyResultSet.first(HikariProxyResultSet.java)
[09:30:34 WARN]: at me.botsko.prism.database.sql.SqlSelectIdQueryBuilder.execute(SqlSelectIdQueryBuilder.java:63)
[09:30:34 WARN]: at me.botsko.prism.actionlibs.ActionsQuery.getQueryExtents(ActionsQuery.java:166)
[09:30:34 WARN]: at me.botsko.prism.purge.PurgeTask.run(PurgeTask.java:66)
[09:30:34 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[09:30:34 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[09:30:34 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[09:30:34 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[09:30:34 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[09:30:34 WARN]: at java.lang.Thread.run(Thread.java:748)
[09:30:34 INFO]: [Prism] Cleared 0 rows. Max cycle time 0 msec. Using: before:8w
```

**Comment by darbyjack** [comment]
Already being fixed via https://github.com/AddstarMC/Prism-Bukkit/pull/258
