### ISSUE TITLE
WorldEdit 7 compatibility

### ISSUE THREAD

**Issue by k-jiang** [AddstarMC/Prism-Bukkit#29]
Prism throw exception while using `r:we` flag. Might need to force convert Vector type?

tested with:
Paper 1.13.2 build 540 https://papermc.io/ci/job/Paper-1.13/540/
WorldEdit 7.0.0-beta-05;6bbf29b https://dev.bukkit.org/projects/worldedit/files/2663452
Prism the latest build (3fac651)

```
[13:14:41 INFO]: kjiang issued server command: /pr l r:we
[13:14:41 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pr' in plugin Prism v2.1.0-${env.BUILD_NUMBER}
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-540]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-540]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-540]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1797) ~[patched_1.13.2.jar:git-Paper-540]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1605) ~[patched_1.13.2.jar:git-Paper-540]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-540]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-540]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-540]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-540]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-540]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-540]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-540]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-540]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.regions.Region.getMinimumPoint()Lcom/sk89q/worldedit/Vector;
        at me.botsko.prism.bridge.WorldEditBridge.getSelectedArea(WorldEditBridge.java:34) ~[?:?]
        at me.botsko.prism.parameters.RadiusParameter.process(RadiusParameter.java:140) ~[?:?]
        at me.botsko.prism.parameters.SimplePrismParameterHandler.process(SimplePrismParameterHandler.java:95) ~[?:?]
        at me.botsko.prism.commandlibs.PreprocessArgs.process(PreprocessArgs.java:95) ~[?:?]
        at me.botsko.prism.commandlibs.PreprocessArgs.process(PreprocessArgs.java:21) ~[?:?]
        at me.botsko.prism.commands.LookupCommand.handle(LookupCommand.java:44) ~[?:?]
        at me.botsko.prism.commandlibs.Executor.onCommand(Executor.java:106) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.2.jar:git-Paper-540]
```

If you need more information or testing, please let me know.

**Comment by k-jiang** [comment]
It seems like I need to do a `mvn clean` before building a new one. Will close this issue.
