### ISSUE TITLE
Sometimes rollback fails or does not complete properly

### ISSUE THREAD

**Issue by addstar** [AddstarMC/Prism-Bukkit#39]
Sometimes during rollback, Prism seems to fail to perform some of the rollback, or possibly doesn't even roll back anything.. I'm not sure how this is handled in code. It would be nice to have these kind of errors handled nicely by skipping over the failures and rolling back what is possible.

This failure was noticed during a 1.14 rollback in Hardcore:
```
[Prism]: Applier error: org.bukkit.craftbukkit.v1_14_R1.block.CraftBlockState cannot be cast to org.bukkit.block.CreatureSpawner
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_14_R1.block.CraftBlockState cannot be cast to org.bukkit.block.CreatureSpawner
  at me.botsko.prism.actions.BlockAction.placeBlock(BlockAction.java:414)
  at me.botsko.prism.actions.BlockAction.applyRollback(BlockAction.java:271)
  at me.botsko.prism.appliers.Preview$1.run(Preview.java:302)
  at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
  at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
  at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1129)
  at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418)
  at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1061)
  at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:905)
  at java.lang.Thread.run(Thread.java:748)
```

Followed by:
```
[Prism]: Applier error: BlockData cannot be null
java.lang.IllegalArgumentException: BlockData cannot be null
  at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
  at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlockState.setBlockData(CraftBlockState.java:105)
  at me.botsko.prism.actions.BlockAction.placeBlock(BlockAction.java:458)
  at me.botsko.prism.actions.BlockAction.applyRollback(BlockAction.java:271)
  at me.botsko.prism.appliers.Preview$1.run(Preview.java:302)
  at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
  at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
  at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1129)
  at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418)
  at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1061)
  at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:905)
  at java.lang.Thread.run(Thread.java:748)
```

**Comment by addstar** [comment]
Closing this until we can confirm this still happens in the new version
