### ISSUE TITLE
Function any_value does not exist

### ISSUE THREAD

**Issue by rumickon** [AddstarMC/Prism-Bukkit#67]
Version: v2.1.3-80

Error after clear install and lookup:
```
[Prism] Database connection error: FUNCTION test_prism.any_value does not exist
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: FUNCTION test_prism.any_value does not exist
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1912)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2020)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at me.botsko.prism.database.sql.SQLSelectQueryBuilder.executeSelect(SQLSelectQueryBuilder.java:517)
	at me.botsko.prism.actionlibs.ActionsQuery.lookup(ActionsQuery.java:81)
	at me.botsko.prism.wands.InspectorWand.lambda$showLocationHistory$0(InspectorWand.java:103)
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by addstar** [comment]
Hi! We've mainly been using Prism with MySQL 5.7 for a long time and I this this error is due to an incompatibility with older versions of MySQL (before 5.7).

Can you try setting `useNonStandardSql: false` in the mysql section of the config and let us know if this fixes it?

**Comment by rumickon** [comment]
DB version: MariaDB-10.2.29
With `useNonStandardSql: false` work perfectly. Thanks.
